Default Parser
jenkinsci/coverage-plugin pull request #148
Opened 2024-05-13 21:40 UTC by pyieh

Change to the plugin behavior when no parser is provided in the tool field. Previous behavior was to error out. Now, the following scenarios can occur with their corresponding behavior:

**_Note_** Simplified error message is in the format: `Attempted parser <PARSER> with pattern <PATTERN>, but was unsuccessful.`

1) No tool is defined (i.e. no parser or pattern) & at least 1 parser is successful:
   - ex call)`recordCoverage(tools: [])`
   - Try each possible parser with its corresponding default pattern
   - Print the successful parsers' logs and a simplified error message for each parser that failed.
   Snippet of example output [Successful Go coverage, rest fail]:    
![image](https://github.com/jenkinsci/coverage-plugin/assets/11794153/c857e767-35f1-48cf-8cbd-f83bd2e14a03)

2) No tool is defined (i.e. no parser or pattern) & all parsers fail 
   - ex call) `recordCoverage(tools: [])`
   - Try each possible parser with its corresponding default pattern
   - Print the logs of each parser tried.
   Snippet of example output [All fail]:
![image](https://github.com/jenkinsci/coverage-plugin/assets/11794153/3bcb3fb8-b333-4cc5-b67d-a80b091d86f3)

3) At least 1 pattern is defined, but none of them have a corresponding parser: 
   - ex call) `recordCoverage(tools: [[pattern: '*coverage.out'], [pattern: '*coverage.xml']])`
   - Try each input pattern with each possible parser. 
   - Follows same ruling as above:
      - 1+ successful -> print verbose logs of successful combination, simplified error message of other combinations
      - All fail -> print verbose logs of all
   Snippet of example output [2 patterns for Go & Python coverage successfully get auto detected]:
![image](https://github.com/jenkinsci/coverage-plugin/assets/11794153/0a7c93d8-0ca1-47de-b5a0-828656c279b0)

**_Note_** Scenario 3 can occur even if another tool with a Parser is defined. Treats the expansion of that tool as 1 set.
ex call) `recordCoverage(tools: [[parser: 'JACOCO'], [pattern: '*coverage.xml']])`

### Testing done
Tested on a local instance of Jenkins running the plugin version. Ran the aforementioned scenarios via pipeline jobs and recorded their builds' console output. 
Also created unit tests that test the same thing.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-05-14 20:05 UTC, uhafner commented
Can you please elaborate why this is useful? Is specifying the parser too complicated in your setup?

2024-05-14 22:19 UTC, pyieh commented
> Can you please elaborate why this is useful? Is specifying the parser too complicated in your setup?

Yeah, our usecase is that we have a number of pipelines (1000+) migrating over that simply upload their coverage files to a server/service that determines the type of coverage file it is for them, so users aren't specifying anything about the specifics of the coverage file type. We want to make the migration to using the `recordCoverage()` call in their pipelines as hands-off and minimal steps as possible, which involved moving the "What type of coverage is this?" determination functionality into the `coverage-plugin`.

2024-05-22 11:58 UTC, uhafner requested changes

2024-05-22 11:58 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorder.java
> +     * - All fail -&gt; Logs all messages
Fix JavaDoc

2024-05-22 11:58 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorder.java
> +        HashMap<CoverageTool, FilteredLog> parsersErrLogs = new HashMap<>();
```suggestion
        Map<CoverageTool, FilteredLog> parsersErrLogs = new HashMap<>();
```

2024-05-22 11:58 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorder.java
> +                catch (InterruptedException | RuntimeException exception) {
Never catch a `RuntimeException`

2024-05-22 11:58 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageToolExpander.java
> +                    tools.add(new CoverageTool(parser, null));
`null` is not a valid parameter

2024-05-22 11:58 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageToolExpander.java
> +public class CoverageToolExpander {
Why is this class and the methods public? It is not part of the API.

2024-05-22 11:58 UTC, uhafner commented on plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoveragePluginITest.java
> -    }
Did  you check Freestyle jobs and the UI configuration if the jobs?

You might also need to adapt the help files

2024-05-22 11:58 UTC, uhafner commented on plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorderITest.java
> +                        + "    recordCoverage tools: []\n"
Does it work with `recordCoverage` without tools as well? Then please add a test.

2024-05-22 11:58 UTC, uhafner commented on plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorderITest.java
> +                .containsPattern("Successfully parsed file .*/jacoco.xml")
Does it say something about JaCoCo? Then please verify that text as well.

2024-05-22 11:58 UTC, uhafner commented on plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorderITest.java
> +                        + "    recordCoverage(tools: [[pattern: '*jacoco.xml'], [pattern: '*cobertura*.xml']])\n"
I'm not sure if it is really worth to the skip the parser names here. 

While this approach works in general, I wonder what does the output look like when you merge the results of different parsers?

2024-05-22 11:58 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageToolExpander.java
> +                if (!(parser == Parser.JUNIT || parser == Parser.NUNIT || parser == Parser.XUNIT)) {
If you want to skip non-coverage files then use `ParserType`. And why do you want to skip these? Because your teams do not use them? This somehow is unexpected to users.

2025-02-24 21:18 UTC, closed without merging