vc coverage
jenkinsci/coverage-plugin pull request #153
Opened 2024-05-16 19:03 UTC by TimSVector

Adding MC/DC, Function, and Function Call coverage. Results being shown in the coverage report and associated graphs. Method coverage not working for some reason.

Testing done
Tested with an expanded Cobertura xml file. Run through multiple configurations on Jenkins server with varying coverage configurations

```[tasklist]
### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-05-17 14:39 UTC, uhafner commented on plugin/pom.xml
> +    <coverage-model.version>0.44.0-SNAPSHOT</coverage-model.version>
Since the model is green now, you can use the incremental artifact: 
https://github.com/jenkinsci/coverage-model/pull/105/checks?check_run_id=25068929880

2024-05-17 14:41 UTC, uhafner commented
Since I don't have a project with test data (including source code) it would be helpful if you can add screenshots of the changed things in the pull request comment.

2024-05-17 18:54 UTC, TimSVector commented
Hi Ulli,

Here’s the screenshots.  Please note that unless you have any of the new metrics, the views will not change and non of this will be present:


  1.  hoverOverDashboard.png – Added new metrics to the hover over on the main Jenkins dashboard
  2.  jobMainCCTrend.png – Added new metrics to this chart.  When any new metrics are present, the chart will change from a filled graph to a line graph
  3.  covRptOverview.png – Added new metrics to the coverage report.  The heat map for new metrics work the same as the original metrics.  Chart changes from filled to line as in #2
  4.  fileMetrics.png – Added new metrics to chart.  When new metrics are present, the additional metrics have new columns and column headers
  5.  tooltip.png – Tooltip code for hover over will display the new metrics as well.

If you want to use the source code, I have it here: https://github.com/TimSVector/PointOfSales_v2.git

TimS

From: Ullrich Hafner ***@***.***>
Sent: Friday, May 17, 2024 10:42 AM
To: jenkinsci/coverage-plugin ***@***.***>
Cc: Schneider, Tim ***@***.***>; Author ***@***.***>
Subject: Re: [jenkinsci/coverage-plugin] Add in coverage metrics from VectorCAST (PR #153)


Since I don't have a project with test data (including source code) it would be helpful if you can add screenshots of the changed things in the pull request comment.

—
Reply to this email directly, view it on GitHub<https://github.com/jenkinsci/coverage-plugin/pull/153#issuecomment-2117759930>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AENYLQ4N4DUVIM6K26AGTRTZCYJLNAVCNFSM6AAAAABH2ZMPFSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJXG42TSOJTGA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-05-20 18:04 UTC, TimSVector commented
Not sure how to solve the Label Checker or PIT errors

2024-05-21 18:11 UTC, uhafner commented
> Hi Ulli, Here’s the screenshots. 

There are no screenshots. Can you edit the description of the PR and add them there? Then everybody can see them in the ChangeLog.

2024-05-21 18:32 UTC, TimSVector commented on plugin/pom.xml
> +    <coverage-model.version>0.44.0-SNAPSHOT</coverage-model.version>
thank you

2024-05-21 18:33 UTC, uhafner reviewed
I try to setup the build locally to actually see the changes... 

It would be also helpful to have some tests for the source code rendering, so I will not break it in future releases. 

You can also add support in the ChecksAPI (`CoverageChecksPublisher`) but this is optional.

2024-05-21 18:33 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageTrendChart.java
> +    /* Line Mode used to indicate whether is hsould be a filled line chart or line chart */
```suggestion
    /* Line Mode used to indicate whether is should be a filled line chart or line chart */
```

2024-05-21 18:33 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/CoverageSourcePrinter.java
> +    private final int[] mcdcPairCoveredPerLine;
Can you move the new visualization into a sub class? Like the MutationSourcePrinter? You can add some additional template methods in the parent if you want to reuse existing functionality.

2024-05-21 18:33 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/CoverageSourcePrinter.java
> +            ).render();
Looks almost the same as the previous code, can you avoid the duplication?

2024-05-21 18:33 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/CoverageSourcePrinter.java
> +    }
The same here. Can't this be simplified so that the three things share a common and a different section?

2024-05-21 18:33 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
> +            if (deltaHeaderLabel != null && deltaHeaderLabel.compareTo("") != 0) {
```suggestion
            if (StringUtils.isNotEmpty(deltaHeaderLabel)) {
```

2024-05-21 18:33 UTC, uhafner commented on plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumn/help-metric.html
> +        <dd>Function call coverage(given as percentage)</dd>
```suggestion
        <dd>Function call coverage (given as percentage)</dd>
```

2024-05-21 18:33 UTC, uhafner commented on plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGate/help-metric.html
> +        <dd>Function call coverage(given as percentage)</dd>
```suggestion
        <dd>Function call coverage (given as percentage)</dd>
```

2024-05-21 18:33 UTC, uhafner commented on plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-details.checks-expected-result
> +||Module Coverage|Package Coverage|File Coverage|Class Coverage|Method Coverage|Line Coverage|Branch Coverage|Instruction Coverage|MC/DC Pair Coverage|Function Coverage|Function Call Coverage
I wonder if it is possible to hide the new metrics if not applicable?

2024-05-21 18:44 UTC, TimSVector commented
1.  Hover Over Dashboard – Added new metrics to the hover over on the main Jenkins dashboard

![hoverOverDashboard1](https://github.com/jenkinsci/coverage-plugin/assets/18580931/2eb9fc9d-57bf-40c2-af6f-b3e0425d6585)

2.  Job Main Code Coverage Trend– Added new metrics to this chart.  When any new metrics are present, the chart will change from a filled graph to a line graph

![jobMainCCTrend2](https://github.com/jenkinsci/coverage-plugin/assets/18580931/c688bee0-0380-4674-9630-65c8c485f320)

3.  Coverage Report Overview – Added new metrics to the coverage report.  The heat map for new metrics work the same as the original metrics.  Chart changes from filled to line as in #2 above

![covRptOverview](https://github.com/jenkinsci/coverage-plugin/assets/18580931/fa0d9d44-bed5-4f9c-a4de-604ebf15b538)

4.  File Metrics – Added new metrics to chart.  When new metrics are present, the additional metrics have new columns and column headers

<img width="1634" alt="fileMetrics" src="https://github.com/jenkinsci/coverage-plugin/assets/18580931/733b0a65-8766-40b1-a74f-7271a4aba76d">

5.  tooltip.png – Tooltip code for hover over will display the new metrics as well.

![tooltip](https://github.com/jenkinsci/coverage-plugin/assets/18580931/9549bda6-00cf-434a-909f-d47ad7f46aa4)

2024-05-28 18:06 UTC, TimSVector commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageTrendChart.java
> +    /* Line Mode used to indicate whether is hsould be a filled line chart or line chart */
complete

2024-05-28 18:09 UTC, TimSVector commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/CoverageSourcePrinter.java
> +            ).render();
complete

2024-05-29 17:51 UTC, TimSVector commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/CoverageSourcePrinter.java
> +    }
complete

2024-05-29 17:53 UTC, TimSVector commented on plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumn/help-metric.html
> +        <dd>Function call coverage(given as percentage)</dd>
Complete

2024-05-30 14:37 UTC, TimSVector commented on plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGate/help-metric.html
> +        <dd>Function call coverage(given as percentage)</dd>
complete

2024-05-30 14:42 UTC, TimSVector commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
> +            if (deltaHeaderLabel != null && deltaHeaderLabel.compareTo("") != 0) {
complete

2024-05-31 19:25 UTC, TimSVector commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/CoverageSourcePrinter.java
> +    private final int[] mcdcPairCoveredPerLine;
complete

2024-05-31 19:25 UTC, TimSVector commented on plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-details.checks-expected-result
> +||Module Coverage|Package Coverage|File Coverage|Class Coverage|Method Coverage|Line Coverage|Branch Coverage|Instruction Coverage|MC/DC Pair Coverage|Function Coverage|Function Call Coverage
@uhafner  - I'm not sure how to achieve this

2024-06-04 09:43 UTC, uhafner commented on plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-details.checks-expected-result
> +||Module Coverage|Package Coverage|File Coverage|Class Coverage|Method Coverage|Line Coverage|Branch Coverage|Instruction Coverage|MC/DC Pair Coverage|Function Coverage|Function Call Coverage
I see, this was already broken before. The table is even shown for mutation results. I think I create an issue and fix this later!

2024-06-04 09:47 UTC, uhafner commented on plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-details.checks-expected-result
> +||Module Coverage|Package Coverage|File Coverage|Class Coverage|Method Coverage|Line Coverage|Branch Coverage|Instruction Coverage|MC/DC Pair Coverage|Function Coverage|Function Call Coverage
FYI: https://issues.jenkins.io/browse/JENKINS-73248

2024-06-04 09:48 UTC, uhafner commented
> @uhafner - I'm not suer what changed to trigger the
> 
> * PIT / Create and archive PIT report (pull_request) Failing after 9m
> 
> It hadn't been happening previously.

The file format changed and this PR result is compared with the result of the main branch. We can ignore this failure.

2024-06-17 07:27 UTC, uhafner requested changes
Looks good now, thanks!

It would be good if we can remove the method coverage as a default visible item as other users are typically not that interested in this derived metric. Most users are interested in the actual value metrics only. I think we can think about such a change (maybe with a configuration option) in an followup pull request.

2024-06-17 07:27 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageTrendChart.java
> +                || dataSet.containsSeries(CoverageSeriesBuilder.METHOD_COVERAGE)
Can we remove this one here? Otherwise existing users will get a line chart now.

```suggestion
```

2024-06-17 07:27 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java
> +                        Metric.MCDC_PAIR, Metric.METHOD, Metric.FUNCTION_CALL));
The same here: existing users are normally not interested in method coverage. You will see all metrics when you open the tooltip. 

```suggestion
                        Metric.MCDC_PAIR, Metric.FUNCTION_CALL));
```

2024-06-17 07:27 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisher.java
> +    public Stream<Metric> getMetricStream() {
This method is only used internal, no need to increase visibility
```suggestion
    private Stream<Metric> getMetricStream() {
```

2024-06-17 07:27 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
> +                "", columns);
Same here, existing users are not interested in method coverage here

2024-06-17 07:27 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
> +        }
see above

2024-06-17 07:27 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel.java
> +            Metric.MCDC_PAIR, Metric.FUNCTION_CALL, Metric.METHOD);
Same here:

```suggestion
            Metric.MCDC_PAIR, Metric.FUNCTION_CALL);
```

2024-06-17 07:27 UTC, uhafner commented on plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-summary.checks-expected-result
> +  * Method Coverage: 95.10% (97/102)
Same here

2024-06-17 13:46 UTC, TimSVector commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisher.java
> +    public Stream<Metric> getMetricStream() {
Complete

2024-06-17 13:47 UTC, TimSVector commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
> +        }
Complete

2024-06-17 13:48 UTC, TimSVector commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel.java
> +            Metric.MCDC_PAIR, Metric.FUNCTION_CALL, Metric.METHOD);
Complete

2024-06-17 13:49 UTC, TimSVector commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java
> +                        Metric.MCDC_PAIR, Metric.METHOD, Metric.FUNCTION_CALL));
Complete

2024-06-17 13:51 UTC, TimSVector commented on plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-summary.checks-expected-result
> +  * Method Coverage: 95.10% (97/102)
Complete

2024-06-18 09:22 UTC, uhafner commented
Did you forget to push your changes?

2024-06-18 12:44 UTC, TimSVector commented
I made the changes and tested, but the tests didn’t pass.  I was still getting method in the return values on tests, so I didn’t push.
________________________________
From: Ullrich Hafner ***@***.***>
Sent: Tuesday, June 18, 2024 5:22:40 AM
To: jenkinsci/coverage-plugin ***@***.***>
Cc: Schneider, Tim ***@***.***>; Author ***@***.***>
Subject: Re: [jenkinsci/coverage-plugin] Add coverage metrics from VectorCAST (PR #153)


Did you forget to push your changes?

—
Reply to this email directly, view it on GitHub<https://github.com/jenkinsci/coverage-plugin/pull/153#issuecomment-2175623496>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AENYLQ77TDXBNNDU5DKTFPTZH736BAVCNFSM6AAAAABH2ZMPFSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNZVGYZDGNBZGY>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-06-19 10:03 UTC, uhafner commented
Hmm, somehow the existing test also fails. I created a temporary PR https://github.com/jenkinsci/coverage-plugin/pull/179 to see if the model is the culprit or the changes here...

I'll have a look at it in more detail.

2024-06-19 19:12 UTC, uhafner commented
I think I fixed the last failure. Can you please parse one of your vector-cast files from the model in the plugin tests (`CoveragePluginITest` or `CoverageRecorderITest`), so we can see that everything works as expected. Maybe a test for the new source code renderer would be helpful as well...

2024-06-20 14:56 UTC, TimSVector commented
I added a new test file for statement+branch, statement+MCDC, and statement+branch+function call (includes function coverage) into VectorCastCoverageChecksPublisherTest.java which is derived from CoverageChecksPublisherTest.java.

Still getting no Method Coverage

2024-06-21 09:12 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageTrendChart.java
> +        // If the dataset contains MCDC, method or Function Call Coverage
```suggestion
        // If the dataset contains MCDC or Function Call Coverage
```

2024-06-21 09:12 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageTrendChart.java
> +
```suggestion
```

2024-06-21 09:12 UTC, uhafner commented on plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/Messages.properties
> +Column.Method=Method
```suggestion
```

2024-06-21 09:12 UTC, uhafner commented on plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/VectorCastCoverageChecksPublisherTest.java
> +import io.jenkins.plugins.coverage.metrics.AbstractCoverageTest;
```suggestion
```

2024-06-21 09:22 UTC, uhafner commented
> I added a new test file for statement+branch, statement+MCDC, and statement+branch+function call (includes function coverage) into VectorCastCoverageChecksPublisherTest.java which is derived from CoverageChecksPublisherTest.java.
> 
> Still getting no Method Coverage

You mean in the overview? The overview shows only value metrics. Details are available as tooltip only. The checks publisher does not show them at all. I can make that overridable if required?

2024-06-21 11:35 UTC, TimSVector commented on plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/VectorCastCoveragePluginITest.java
> +                .extracting(TableModel::getColumns).asList()
Reuse existing test code

2024-06-21 17:02 UTC, uhafner approved these changes
I fixed the display of the method coverage in the checks result. 

On the tabs this metric is not shown intentionally as it is an aggregated metric and not a value metric. It should be visible in the bar chart though, I need to create a build with this chart...

2024-06-21 17:07 UTC, uhafner commented
Your test case `shouldParseFileWithVectorCast` produces this chart:

![Bildschirmfoto 2024-06-21 um 19 06 20](https://github.com/jenkinsci/coverage-plugin/assets/503338/88e9c20d-3d75-4d2c-9b87-830c35ba63df)

It seems that the method coverage is shown.

2024-06-21 19:10 UTC, TimSVector commented
> It seems that the method coverage is shown.

Where would that image be when I run locally?

2024-06-21 20:45 UTC, uhafner commented
> > It seems that the method coverage is shown.
> 
> Where would that image be when I run locally?

Add a breakpoint after `buildWithResult`. Then in the console you will find something like:

```
Connected to the target VM, address: '127.0.0.1:50392', transport: 'socket'
   0.058 [id=1]	INFO	o.jvnet.hudson.test.WarExploder#explode: Picking up existing exploded jenkins.war at /Users/hafner/git/warnings-ng-plugin-devenv/coverage-plugin/plugin/target/jenkins-for-test
   0.419 [id=1]	INFO	o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:50398/jenkins/
   0.829 [id=48]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
   4.774 [id=51]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
   4.815 [id=54]	INFO	j.b.api.BouncyCastlePlugin#start: 
```

Click on the link and you will see the Jenkins under test. (Make sure that you enable the breakpoint option `Suspend Thread`, otherwise the UI is halted as well).

2024-06-24 15:44 UTC, TimSVector commented
I see it in debug.  I'm going to create a new project in Jenkins and see if that helps.

I would like to see Method coverage when there is Function Call and/or MCDC Pairs.

2024-06-26 09:05 UTC, uhafner commented
I created a release of the coverage model now. There is also a bugfix in this release for the merge operations (https://issues.jenkins.io/browse/JENKINS-73352).   

Would it be ok, if I release this PR right now and we can look afterwards in followup PRs on how to configure other UI elements differently?

2024-06-26 12:53 UTC, TimSVector commented
Yes – that would be fine

From: Ullrich Hafner ***@***.***>
Sent: Wednesday, June 26, 2024 5:06 AM
To: jenkinsci/coverage-plugin ***@***.***>
Cc: Schneider, Tim ***@***.***>; Author ***@***.***>
Subject: Re: [jenkinsci/coverage-plugin] Add coverage metrics from VectorCAST (PR #153)


I created a release of the coverage model now. There is also a bugfix in this release for the merge operations (https://issues.jenkins.io/browse/JENKINS-73352).

Would it be ok, if I release this PR right now and we can look afterwards in followup PRs on how to configure other UI elements differently?

—
Reply to this email directly, view it on GitHub<https://github.com/jenkinsci/coverage-plugin/pull/153#issuecomment-2191192398>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AENYLQ6GQ2IQHZGDU2RNE33ZJJ77JAVCNFSM6AAAAABH2ZMPFSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJRGE4TEMZZHA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-06-26 14:39 UTC, merged