Added code to visualise metrics
jenkinsci/coverage-plugin pull request #213
Opened 2024-08-12 13:51 UTC by maxwai

This adds the extracted metrics from https://github.com/jenkinsci/coverage-model/pull/119 to the web report.

### Testing done

Tested with https://github.com/uhafner/warnings-ng-plugin-devenv 

Adds a new Report named "Metrics"

![image](https://github.com/user-attachments/assets/f5624e4b-2b9f-48c0-b031-994b953f470b)

![image](https://github.com/user-attachments/assets/af6df82c-a0a4-4efc-a507-0fbd72924877)

The Metrics are show the same as Line Coverage

![image](https://github.com/user-attachments/assets/15571832-5e17-4911-8e73-a0b11f744af3)

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-08-19 09:11 UTC, uhafner commented on plugin/pom.xml
> +    <coverage-model.version>0.47.0</coverage-model.version>
```suggestion
    <coverage-model.version>0.47.0-rc814.b_47b_7415c6dd</coverage-model.version>
```

The latest snapshot version is visible in the incrementals check result:

<img width="735" alt="Bildschirmfoto 2024-08-19 um 11 11 07" src="https://github.com/user-attachments/assets/3eef45be-3506-45f1-9c18-2d33fa9ad515">

2024-09-20 15:47 UTC, uhafner requested changes
Thanks! Looks already really good!

2024-09-20 15:47 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/charts/CoverageSeriesBuilder.java
> +        }
For now this is ok, but in the future it would make more sense to have a specific model for the metrics.

2024-09-20 15:47 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java
> +                    .map(value -> value instanceof Coverage && ((Coverage) value).getCovered() != 0)
Would it be sufficient to check for `Coverage#isSet`?

2024-09-20 15:47 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageJobAction.java
> +        return new CoverageTrendChart().create(iterable, ChartModelConfiguration.fromJson(configuration), false);
In the future it makes sense to have a specific trend chart in the job display for metrics as well.

2024-09-20 15:47 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
> -                    .withDetailedCell()
I think this is the problem why the complex object is not correctly rendered.

2024-09-20 15:47 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
> +            }
Nice simplification! Java is sometimes so verbose 🙈

2024-09-20 15:47 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTool.java
> +                "symbol-footsteps-outline plugin-ionicons-api");
Maybe a ruler (font awesome `ruler-vertical`) or scale (font awesome `scale-balanced`) would match better?

2024-09-20 15:47 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel.java
> +            }
Should be a method in coverage-model.

2024-09-20 15:47 UTC, uhafner commented on plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/index.jelly
> +              <div id="metrics-trend" class="graph-cursor-pointer overview-chart h-100"/>
We should only show metrics when we have more than one. 

Wouldn't it make more sense if we create a new tab for the metrics, that shows only the metrics overview? Then we show both tabs if we have data for both, and only one tab if there is data from a single category?

2024-09-20 15:47 UTC, uhafner commented on plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/index.jelly
> +            <div id="project-${metric.toTagName()}" class="graph-cursor-pointer tree-chart" data-item-name="project-${metric.toTagName()}"/>
Why has this been changed?

2024-11-12 12:22 UTC, maxwai commented on plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/index.jelly
> +            <div id="project-${metric.toTagName()}" class="graph-cursor-pointer tree-chart" data-item-name="project-${metric.toTagName()}"/>
If left as is, the data name was always the same, this was needed to be able to distinguish between the different metrics

2024-11-12 12:25 UTC, maxwai commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
> -                    .withDetailedCell()
should this function call be used with every metric? Because before it was only used for the complexity density but I can't see the different between the density and the complexity maximum for example

2024-11-12 20:21 UTC, uhafner commented on plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTableModel.java
> -                    .withDetailedCell()
Only for the complexity density. The reason is that the detailed cell has a special rendering for this attribute. The others simply use the property getter. 

But since I removed COMPLEXITY_DENSITY in the meantime from the model it is ok to leave the code as it is. I will remove this column anyway in the next release!

2024-11-12 20:21 UTC, uhafner commented on plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/index.jelly
> +            <div id="project-${metric.toTagName()}" class="graph-cursor-pointer tree-chart" data-item-name="project-${metric.toTagName()}"/>
OK

2025-02-17 22:13 UTC, merged